
version: 2
jobs:
  frontend:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: PGHOST=localhost EXTERNAL_HOST=http://localhost:3000 npm test

  backend:
    docker:
      - image: circleci/node:latest
      - image: circleci/postgres:latest

    working_directory: ~/repo/cli

    steps:
      - checkout:
          path: ~/repo/backend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm test
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  everything:
    jobs:
      - frontend
      - backend
